django_apps/django_apps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taskapp/', include("taskapp.urls")),
    path('pollapp/', include("pollapp.urls")),
]

django_apps/pollapp/urls.py
from django.urls import path
from . import views

urlpatterns= [
    path('', views.index, name= 'index')
]

django_apps/taskapp/urls.py
from django.urls import path
from . import views

app_name= "taskapp"
urlpatterns= [
    path("", views.index, name = "index"),
    path("add_task/", views.add, name = "add_task"),
]

django_apps/pollapp/models.py
from django.db import models

# Create your models here.

django_apps/taskapp/models.py
from django.db import models

# Create your models here.

django_apps/pollapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Hello World")

django_apps/taskapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse

# Create your views here.


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task: ", min_length=1, max_length=100)

def index(request):
    if 'tasks' not in request.session:
        request.session['tasks'] = []

    return render(request, "taskapp/index.html", {
        "tasks": request.session['tasks']
    })

def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session['tasks'] += [task]
            return HttpResponseRedirect(reverse("taskapp:index"))
    
    else:
        form= NewTaskForm()

    return render(request, "taskapp/add_task.html", {
        "form": form
    })

django_apps/taskapp/templates/taskapp/add_task.html
{%extends "taskapp/layouts.html"%}

{%block body%}

    <h1>ADD TASK</h1>
    <form action="{% url 'taskapp:add_task' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="SUBMIT">
    </form>
    
    <a href="{% url 'taskapp:index' %}">VIEW TASKS</a>

{%endblock%}

django_apps/taskapp/templates/taskapp/index.html
{%extends "taskapp/layouts.html"%}

{%block body%}
    
    <h1>TASK MANAGER</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {%endfor%}
    </ul>
        
    <a href="{% url 'taskapp:add_task' %}">ADD NEW TASK</a>

{%endblock%}

django_apps/taskapp/templates/taskapp/layouts.html
{%load static%}
<!DOCTYPE html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TASK APP</title>
    <link rel="stylesheet" href="{%static '/taskapp/style.css' %}">
</head>
<body>
    <div class="section">
        {% block body %}

        {% endblock %}
    </div>
</body>